### ISSUE TITLE
Non-deterministic segfaults

### ISSUE THREAD

**Issue by wolfv** [lief-project/LIEF#814] opened 2022-10-23 04:36 UTC
Hi, in the conda-forge project we're happy users of the latest version of `LIEF`. 
Unfortunately, we've been experiencing some non-deterministic segfaults of builds. You can find one here: https://github.com/mamba-org/mamba/actions/runs/3294084530/jobs/5431246479

There are quite a few more in the `conda-forge` project (it runs LIEF after every build). Unfortunately I don't have a way to reproduce. Usually rerunning the build fixes things.

Maybe using some of the sanitizer tools could help?

**Comment by romainthomas** [comment] 2022-10-25 04:37
Hi @wolfv 
That's weird, and yes I regularly run the sanitizers: https://github.com/lief-project/LIEF/tree/master/tests/sanitizer

From the log I can't see in the input file. Could you save the binary on a failure? 

(By the way I fixed the logs)

**Comment by wolfv** [comment] 2022-10-29 08:05
OK, finally we got a case :)

On this pipeline the osx-64 static build failed at the LIEF stage: https://github.com/mamba-org/mamba/actions/runs/3346675396

I am not sure if you can download the artifact. I have uploaded the micromamba binary here: https://drive.google.com/file/d/1qtdglwTlVY_6JrwhXeyjAc-b0-dv0w0r/view?usp=sharing

I think the code in conda-build that uses lief is mostly here: https://github.com/conda/conda-build/tree/e4d9b3bd255565d47b6ab6b93380ef246b2a1ddf/conda_build/os_utils to extract linked libraries.

I can try – over the next couple of days – to isolate the code that uses lief better to pinpoint the issue.

**Comment by wolfv** [comment] 2022-10-30 13:39
I wrote a quick & hacky script to try and debug this, but couldn't reproduce the segfault:

```py
import os
from pathlib import Path
folder = Path("~/Downloads/")
host = '/Users/wolfvollprecht/Downloads/Users/runner/micromamba-root/envs/mambabuild/conda-bld/micromamba_1666973363570/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/'

from conda_build.post import *

class Config:
    build_folder = os.path.dirname(host)
    build_prefix = os.path.join(build_folder, "_build_env")
    host_platform = "osx"
    target_subdir = "osx-arm64"
    error_overlinking = False
    error_overdepending = False
    verbose = True
    bldpkgs_dir = '/Users/wolfvollprecht/micromamba/conda-bld'
    output_folder = '/Users/wolfvollprecht/micromamba/conda-bld'
    channel_urls = '/Users/wolfvollprecht/micromamba/conda-bld'
    # ???
    enable_static = True
    variant = {}

meta = {
    "package": {
        "name": "micromamba",
    },
    "build": {
        "number": 0,
        "string": "xxx"
    }
}

class Meta:
    def get_value(self, s, default=None):
        if s == "build/rpaths":
            return default
        el = meta
        for key in s.split('/'):
            el = el.get(key)
            if not el:
                return default
        if el:
            print(f"Found: {s}: {el}")
            return el

        return default

    meta = {}
    config = Config()

def post_build(files, build_python, host_prefix=None, is_already_linked=False):
    print('number of files:', len(files))
    m = Meta()
    if not host_prefix:
        host_prefix = host

    if not is_already_linked:
        for f in files:
            make_hardlink_copy(f, host_prefix)

    if True:
        binary_relocation = True
        if not binary_relocation:
            print("Skipping binary relocation logic")
        # osx_is_app = (m.config.target_subdir.startswith('osx-') and
        #               bool(m.get_value('build/osx_is_app', False)))
        osx_is_app = False
        check_symlinks(files, host_prefix, False)
        prefix_files = utils.prefix_files(host_prefix)

        for f in files:
            if f.startswith('bin/'):
                fix_shebang(f, prefix=host_prefix, build_python=build_python,
                            osx_is_app=osx_is_app)
            if binary_relocation is True or (isinstance(binary_relocation, list) and
                                             f in binary_relocation):
                post_process_shared_lib(m, f, prefix_files, host_prefix)
    check_overlinking(m, files, host_prefix)

if __name__ == "__main__":
    mm = os.path.join(host, "bin/micromamba")
    libs = []
    # libs = list((Path(host) / "lib").rglob("*.dylib"))
    # libs += list((Path(host) / "lib").rglob("*.a"))
    # libs = [str(l) for l in libs]
    post_build([mm] + libs, "")
```

**Comment by romainthomas** [comment] 2022-11-01 05:03
I downloaded the binary (`micromamba-osx-64-lief-debug`) and I run both: sanitizers and a basic script that reads all the Mach-O attributes but I can't reproduce the segfault. 

Could you somehow get a backtrace (even if the symbols are missing) when it crashes?

**Comment by wolfv** [comment] 2022-11-01 08:14
I have another binary (osx-arm64 this time) that segfaults in CI, but locally I also could not get it to segfault. It does print some more logs, though:

CI Run: https://github.com/mamba-org/mamba/actions/runs/3363314143/jobs/5576280399
Logs: https://gist.github.com/wolfv/b2f372c5186ed2943e6769759658b464
micromamba binary: https://drive.google.com/file/d/1H0s_nG8Aphuf-liRrwPZ7sAEvNtMDJfL/view?usp=share_link

I'll try some more to reproduce the issue.

**Comment by wolfv** [comment] 2022-11-01 08:16
Ah, and the lief-logs that I linked are produced locally with `INFO` level. I also tried `TRACE` but it prints too many symbols. If you are interested, I can also paste that.

Not sure if this is a hint? `Relocation #140 of __StaticInit seems corrupted: r_symbolnum is 288 sections.size(): 9`

**Comment by romainthomas** [comment] 2022-11-02 06:27
Could you also try with the nightly package (https://lief.s3-website.fr-par.scw.cloud/latest/lief/) to verify whether the error has not been fixed (somehow) in master.

**Comment by wolfv** [comment] 2022-11-02 07:43
@romainthomas yes, definitely. We're about to release 0.12.3 into conda-forge, let's see if that changes things :) (it could!) https://github.com/conda-forge/lief-feedstock/pull/36#issuecomment-1299577904

Also, is there a way to get rid of the `LINKER_OPTIMIZATION_HINT not parsed` message? Maybe I should open a new issue for that.

**Comment by romainthomas** [comment] 2022-11-12 09:44
For the multiple `LINKER_OPTIMIZATION_HINT not parsed` warnings, I pushed a fix: https://github.com/lief-project/LIEF/commit/e7eaa8e7534f25642d90c0ae7aceb47188df9d8e

**Comment by wolfv** [comment] 2022-11-12 12:46
Cool! Thanks

**Comment by wolfv** [comment] 2023-01-03 10:10
I'll close this for now as I wasn't able to produce any more reproducers :) Also looks like things are better now! Thanks for LIEF.

**Comment by romainthomas** [comment] 2023-01-03 14:02
Thank you as well :)

**Closed by romainthomas** 2023-01-03 14:02 UTC
Labels: bug, MachO
